### ISSUE TITLE
Inform users of country_select 2.0 Changes

### ISSUE THREAD

**Issue by scudco** [heartcombo/simple_form#1116]
I'm one of the maintainers of the `country_select` gem, and I wanted to raise a few flags about how the upcoming 2.0 release could affect `simple_form` users.

`country_select` 2.0 now uses ISO-3166 country codes by default. Simple Form is still fully supported, but since the simple_form documentation simply says to include `gem 'country_select'` to gain that functionality, it could create breakages for users currently storing countries as strings rather than codes.

I've provided a note about upgrading from 1.x [here](https://github.com/stefanpenner/country_select/blob/master/UPGRADING.md)

Before I release 2.0 onto rubygems I just to give you all a headsup and chance to prepare if necessary.

**Comment by carlosantoniodasilva** [comment]
Hey guys, I've pushed up a [branch testing country select 2.1.0](https://github.com/plataformatec/simple_form/compare/ca-country_select), and it seems from our side there's no required change to make it work.

We should, however, add a note for people upgrading about the gem that now uses the country codes as values rather than the country names as version 1.x, so they should be aware of that. We can also point to this great upgrading doc that @scudco linked, thanks for that btw.

I also noticed that the helper method signature changed slightly to accept `priority_countries` as a hash option rather than a normal parameter. We can't change that on Simple Form without forcing people to upgrade country select (if they are using the integration), so I'd rather stick with the 1.x syntax which is still supported, and do this move when we bump Simple Form to 4.x. This could also be a problem with Rails' `time_zone_select` (we internally use the same implementation to delegate to both), since it uses the same api as 1.x, but we'll figure that out.

One thing that I sort of disliked was the change on value of the disabled option, it now is `---------------` rather than an empty value as before, and I'm not sure whether that was a necessary change or just a side effect. Since the option is disabled it is unlikely to affect anyone, but it was caught by our tests and updated them accordingly to show the change and discuss with you.

So the plan would be:

* Update our tests to be compatible with country select 2.x (as in my branch)
* Add a changelog note explaining about the upgrade and linking to that doc (and maybe on the readme too)
* Wait for SF 4 to update our method signature and officially drop compatibility with country select 1.x

I'm adding @stefanpenner to the loop as we worked together with the integration in the past and we briefly talked about country select v2 a couple times.

Any thoughts? :heart:

**Comment by scudco** [comment]
Sorry I must've missed @rafaelfranca's response in November :(

I think the `-------------` thing could be considered a bug we can fix in the next patch release of country_select.

I realized after country_select 2.0 was finished that `time_zone_select` used the same priority syntax as the 1.x `country_select` so I'm conflicted about whether or not that syntax should really be removed. It's bad, but the breakage may be worse :|

Not sure if any of that helps, but if anything we can do in `country_select` to make it easier for simple_form users, please let me know.

**Comment by netwire88** [comment]
@scudco Are there updated example of `country_select` with `simple_form`? The example here seems broken: https://github.com/scudco/country_select_test/blob/master/app/views/welcome/_simple_form_form.html.erb. For example, it references `only` option but simple_form says to use `collection`. I've tried multiple iterations but for some reason, the actual country, while it's saved, isn't being displayed in simple_form as selected.

**Comment by scudco** [comment]
@netwire88 I haven't updated the gems in that example app in a while. I'll do that and get back to you.

**Comment by scudco** [comment]
@netwire88 I think the simple_form README needs to be updated to not use the `collection` option for country_select. Either that, or it needs to correctly translate `collection` to map to `only` for country `select` tags.

From what I've seen in the simple_form code, `collection` is a generic option for multi-choice inputs specifying an exact set of items to be used to generate choices (`option` tags within a `select` in our case). This means that it fully overrides the `option` tags that `country_select` generates. If you use the latest version of `simple_form` with the latest version of `country_select`, then I believe you should have no problems if you follow the syntax demonstrated in https://github.com/scudco/country_select_test/blob/master/app/views/welcome/_simple_form_form.html.erb
