### ISSUE TITLE
Input file raises error when is the only input on the field and the form is sent empty

### ISSUE THREAD

**Issue by maurogeorge** [heartcombo/simple_form#1153]
Today if the only input we have in a form is a input type file like this:

``` slim
  = simple_form_for @document do |f|
    = f.input :image
    = f.button :submit
```

And we try to submit without fill the image, we got a `ActionController::ParameterMissing - param is missing or the value is empty: document` since nothing is sent on the form.

Maybe we can set a hidden input with value as empty, like was done on the `collection_check_boxes`

**Comment by kohheepeace** [comment]
For those who came by google search as I did:

To prevent errors when submitting form with empty values, set the following on the controller.

`params.fetch(:document, {}).permit(...)` 👈 this means set `{}` empty object as default value

 instead of

`params.require(:document).permit(...)`

Ref:
https://github.com/rails/rails/issues/17947#issuecomment-225154294
