### ISSUE TITLE
Remote Forms w/ File Upload not working correctly

### ISSUE THREAD

**Issue by tonyvince** [heartcombo/simple_form#1658]
## Environment

- Ruby **ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]**
- Rails **5.1.6**
- Simple Form **4.0.1**

## Current behavior

```
<%= simple_form_for @article, remote: true, authenticity_token: true do |f| %>
  .
  <%= f.input :file, as: :file %>
<%= end %>
```

When the form is submitted, an HTML request is registered on the server and not a JS one. `remote: true` in this case is not working when a file is selected. Working correctly when no file selected for upload.

## Expected behavior

The form should be submitted via Ajax

**Comment by feliperenan** [comment]
H @tonyvince, thanks for the issue report. 

Could you please provide us a sample application that reproduces the issue in isolation? 

That would help us find the issue.

**Comment by swigrid** [comment]
hello @feliperenan , 

I have reproduced the issue and uploaded sample app

https://github.com/swigrid/rails_5_0_7_2

as soon as you add an image it is processing request as HTML
`Started POST "/users" for ::1 at 2020-09-28 11:21:05 +0200
Processing by UsersController#create as HTML`

otherwise without an image it's working OK
`Started POST "/users" for ::1 at 2020-09-28 11:23:11 +0200
Processing by UsersController#create as JS`

**Comment by carlosantoniodasilva** [comment]
@swigrid thanks for the sample app.

Have you been able to try/reproduce it without SimpleForm, i.e. just with `form_for`? Just wondering if we can rule it out being SimpleForm there on a quick test.

**Comment by swigrid** [comment]
@carlosantoniodasilva you are actually right, this doesn't seem to be simple_form issue. There is same behaviour with `form_for`. This issue can be probably closed.

**Comment by carlosantoniodasilva** [comment]
Thanks for confirming @swigrid! I'm gonna go ahead and close, if anyone is able to reproduce with SimpleForm we'll be happy to reopen and dig further.
