### ISSUE TITLE
radio_buttons + label:false not working

### ISSUE THREAD

**Issue by yshmarov** [heartcombo/simple_form#1690]
when using `as: :radio_buttons`, label is present event if `label: false `is added.

## Current behavior

`= f.association :service, collection: Service.all, as: :radio_buttons, label: false
`
=> Label is still visible

## Expected behavior

=> Label is removed

**Comment by feliperenan** [comment]
Could you please provide us a sample application that reproduces the issue in isolation? 

That would help us find the issue.

**Comment by davelens** [comment]
@yshmarov I know this is months old, but I *think* I had the same issue you did. SimpleForm renders `vertical_collection` inputs with a `<legend>` element instead of a `label`, even though it will use the label's text. If you replace your line:
```haml
f.association :service, collection: Service.all, as: :radio_buttons, label: false
```
with this:
```haml
f.association :service, collection: Service.all, as: :radio_buttons, label_text: false
```
I'm willing to bet it'll fix the problem you had.

**Comment by pacso** [comment]
I have the same issue, and the suggestion above half-fixes it. It empties the `<legend>` element, but does not remove it from the generated HTML. Whilst you could style the legend to have zero size or `display: none`, it would be nice for it not to be there in the first place when using `label: false`

**Comment by bovender** [comment]
Had the same problem.

@davelens' workaround makes the labels disappear, thanks.

@pacso's comment is true, the empty `<legend>` elements disrupt my layout ever so slightly, but it's better than the labels.

**Comment by nashby** [comment]
Hey! It would be hard to make `label: false` work here since `vertical_collection` wrapper doesn't use `label` component but `label_text` one. To make `legend` disappear when `label_text: false` you can add `unless_blank: true` option to the wrapper here https://github.com/heartcombo/simple_form/blob/21148b319bc9740af7580ecc44826df7bf5c5fcc/lib/generators/simple_form/templates/config/initializers/simple_form_bootstrap.rb#L82. So it'll look like this:

```ruby
b.wrapper :legend_tag, tag: 'legend', class: 'col-form-label pt-0', unless_blank: true do |ba|
  ba.use :label_text
end
```
