### ISSUE TITLE
Select with a search box

### ISSUE THREAD

**Issue by ritaly** [heartcombo/simple_form#1691]
## Current behaviour

Currently, we can create select input with a collection.

`<%= f.input :country_id, collection: countries %>`

## Expected behaviour

It would be convenient to have select with insert and filtering for a long select list.
![select](https://user-images.githubusercontent.com/7140255/75229251-d570f880-57b1-11ea-8958-2c5cf5059a9b.png)

![search](https://user-images.githubusercontent.com/7140255/75229397-1ec14800-57b2-11ea-99f7-d1d271abb5d7.png)

**Comment by feliperenan** [comment]
Hi @ritaly :wave: 

That is not a feature we'd like to support and/or maintain on Simple Form since this project is more focused on providing helpers for you to easily build Rails form. I'd rather implement this kind of feature with Javascript or use some library that does this kind of work on top of the generated input.

Thanks for the proposal though :+1:
