### ISSUE TITLE
Form File Field Multiple File Support 

### ISSUE THREAD

**Issue by jonmchan** [heartcombo/simple_form#1745]
## Current behavior

For a model with `has_many_attached :images`, the form builder builds a file_field with a single file input. 

## Expected behavior

It would be beneficial if simple_form can detect that it is many attached and not has_one_attached and utilize a multiple select file_field (`f.file_field :images, multiple: true`). Adding `f.input :images, multiple:true` does not pass the options to the generator.

**Comment by jonmchan** [comment]
I was able to get this working with `<%= f.input :images, as: :multi_file, input_html: { multiple: true } %>`, but this does not seem correct. The documentation states `Simple Form inputs accept the same options as their corresponding input type helper in Rails`. There seems to be missing options or something improperly wired up for the file input.

**Comment by nashby** [comment]
@jonmchan could you please provide sample app that reproduces it? I just tried `<%= f.input :images, input_html: { multiple: true } %>` and it works fine. I'll reopen if it's reproducible.

**Comment by jaredmoody** [comment]
I was surprised by this as well. I think @jonmchan stated it pretty clearly above, but I'll try and restate:

The way the documentation is worded, it seems that parameters passed _directly_ to the`input` method should be passed down to the rails helper, but in the case of the file input they are not. It does not state that `input_html` is where you should place options to be passed directly down to the helper, but that is where you have to place them.

So while yes, this correctly generates : `<%= f.input :images, input_html: { multiple: true } %>`

I wouldn't expect to have to do that. Per the documentation, `<%= f.input :images, multiple: true %>` should produce the same result since `multiple` is an option the Rails helper takes.

I'll note additionally that the same issue exists with `direct_upload` which is _not_ an html option yet has to be placed in `input_html` to work.

If this isn't a bug, perhaps the documentation should be updated.

**Comment by jonmchan** [comment]
Thank you for articulating @jaredmoody

**Comment by nashby** [comment]
Hey @jaredmoody, thanks for an explanation! I still think that it works correctly since `multiple` is default html option of the file input, it's not something specific to Rails. Same goes e.g for `accept` option of file input. Since it's html input's option it goes to `input_html`. 

If we're talking about something like Rails's `date_select` you can see this

```
date_select(object_name, method, options = {}, html_options = {})
```
so it accepts both Rails specific options as `start_year`, `end_year`, etc and html options as `class`, `id`, etc. So when you use it in SimpleForm you pass `start_year` as regular option and `class` as `input_html`. Does it make sense? Please send a PR with documentation update if you think we can clarify it better.

P.S Yeah, `direct_upload` is something specific since it's not really html option but since it's goes alongside with other options in Rails I think it's ok that we have to pass it as `input_html` option.
