### ISSUE TITLE
`:selected` does not work with html5 datetime

### ISSUE THREAD

**Issue by Silex** [heartcombo/simple_form#1776]
## Environment

- Ruby 2.7.5
- Rails 6.1.4.4
- Simple Form 5.1.0
- Browser chrome.

## Current behavior

I have the following code:

``` ruby
class DateTimeInput < SimpleForm::Inputs::DateTimeInput
  private

  def use_html5_inputs?
    input_options.fetch(:html5, true)
  end
end
```

With a custom from like this

``` haml
= simple_form_for(:files, url: files_album_path(@album), method: :get) do |f|
  = f.input :from, label: from, as: :datetime, include_blank: true, selected: @from, required: false #, input_html: { value: @from.strftime('%FT%T') }
```

The html input is empty. The work around is to uncomment the `input_html` part.
Note that even using `@from.iso8601` does not work as it doesn't like the `+200` at the end of the string.

Using `html5: false` also fixes the problem but the input is then "ugly" 😅 

## Expected behavior

The html input should be correctly filled when using html5.

**Comment by nashby** [comment]
Hey! I believe it's expected behavior. When you use html5 inputs `datetime` uses `datetime_field` from Rails and it's regular input field with `datetime-local` type. So it's not a `select` that's why `selected` option doesn't work since there's nothing to select. Since `selected` option is not something that SimpleForm is introduced (it's regular Rails's option) I don't think we should support it with html5 inputs

**Comment by Silex** [comment]
So we are supposed to use `input_html`?

**Comment by nashby** [comment]
yes. or alternatively you can use form object where you set your value so you don't have to set it in the view
