### ISSUE TITLE
Can't remove label with label: false with as: :check_boxes option. Label also causes misalignment

### ISSUE THREAD

**Issue by 1990eam** [heartcombo/simple_form#1783]
## Environment

- Ruby: 2.7.6
- Rails: 7
- Simple Form: Latest

## Current behavior
I'm setting up an input with the following options: `label: false, as: :check_boxes` . 

The label is not removed and also causes a misalignment where the first checkbox in the collection is to the right of the label.

Tried `label: false` with a selector type input and label is removed as expected.

![09julio2022_13-45-35](https://user-images.githubusercontent.com/46629749/178115141-5cd68fff-8823-4e85-b16d-da658334a9b1.png)

## Expected behavior
Label removed.

Code:

```
<div>
    <%= c.input :service_managers, collection: employees_for_selector, label: false, as: :check_boxes %>
</div>

```

The behaviour seems to have been reported at least once [here](https://github.com/heartcombo/simple_form/issues/1194#issuecomment-903124453).

**Comment by nashby** [comment]
Hey! 

There're couple of things to mention why this works like this:

- This css issue on your screenshot. It's not really a SimpleForm's issue but Bootstrap's. See how's it's handled in https://github.com/heartcombo/simple_form-bootstrap/blob/a130302e607c913fc7b578b3b180e40166218e32/app/assets/stylesheets/simple_form-bootstrap/_form_legend_clear.scss
- `label: false` works when you're not using extra wrapper on label element but since you're using Bootstrap configuration (as far as I can see) then you can disable it with `label: false`. In you're case you can do it with `legend_tag: false` (or whatever wrapper you're using in your config, my example is for default bootstrap config) to disable outer wrapper for that label (and it'll disable label itself).
